### ISSUE TITLE
Loading 3rd party cogs

### ISSUE THREAD

**Issue by majknez** [JonasBonno/docker-discordbot#3]
How can i load 3rd party cogs with docker container?

**Comment by majknez** [comment]
and edit  and update the code in container if im trying to develop cogs

**Comment by JonasBonno** [comment]
I would not recommend using the container for developement.

It would be better instead use a dedicated installation on a server. 
See thier installation guides here: https://github.com/Cog-Creators/Red-DiscordBot#installation
