### ISSUE TITLE
WebSocket connection to server isn't in open state.

### ISSUE THREAD

**Issue by Niccii03** [JonasBonno/docker-discordbot#5]
why do I get the error in my discord server: WebSocket connection to server isn't in open state?

**Comment by JonasBonno** [comment]
@Niccii03 on a fresh install of the docker container or what happen right before the error? Have you deployed it as I wrote in the README with --volumes-from to another container for persisted storage? Is the problem fixed if you try creating a new container?

**Comment by JonasBonno** [comment]
I am closing this issue due to I am not able to reproduce the issues.
By the way I just added a new docker build version 3.4.16 you could try.
